name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: rdf
        environment-file: pyproject.toml
        python-version: ${{ matrix.python-version }}

    - name: run tests
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install pytest
        pip install pytest-cov
        #pytest tests/
        pytest --cov-report=xml --cov=src/atomid tests/